- name: passing variable values through command line
  hosts: localhost
  vars:
    course: devops
    trainer: sriram
  tasks:
    - name: print the variable values
      ansible.builtin.debug:
        msg: course is {{course}} and trainer is {{trainer}}  

    