- name: variables in ansible
  hosts: node
  vars:
   course: devops
   trainer: sriram
   duration: 110hrs
  tasks:
    - name: print the message
      ansible.builtin.debug:
        msg: Iam learning ansible
    - name: print the variables
      ansible.builtin.debug:
        msg: "{{course}}" is one of the most trending tech and trainer is {{trainer}} and duration is {{duration}}     